# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Dane Gauthier
#title: Your job title
email1: Dane@danegauthier.tech
email2: Danegauthier@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dane-gauthier
linkedin_username: danegauthier
resume_username: dane-gauthier

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hey, I’m Dane Gauthier. I’ve been solving desktop and cloud tech challenges for over 15 years, with a current focus on Azure Virtual Desktop. I’m exploring my next opportunity, and I put this together to share a bit of how I think and what I can bring to a team.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  
        title: danegauthier.tech
        link: github.com/dane-gauthier/danegauthier.github.io
        link_text: dane-gauthier/danegauthier.github.io
        additional_links:
          - title: github.com/dane-gauthier/danegauthier.github.io
            icon: fab fa-github
            url: github.com/dane-gauthier/danegauthier.github.io
        quote: >
           
        description: | # this will include new lines to allow paragraphs
         The resume site is Jekyll theme that I learned how to change everything on it. This taught me about static generated sites, GitHub, and Docker. 
  - title: Experience
    layout: list
    content:
      - layout: left
        title: TEKsystems – Thyssenkrupp Materials 
        sub_title: Azure Virtual Desktop Specialist
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: TEKsystems - CONA Services 
        sub_title: Senior IT Support Specialist
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: Scientific Games
        sub_title: End-User Computing Engineer
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: Artivion
        sub_title: Information Systems Specialist III
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: Hays – UCB Pharma 
        sub_title: Desktop Support Technician
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: Compucom
        sub_title: Lead Field Refresh Technician
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: CBM Technology
        sub_title:  IT Specialist
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
      - layout: left
        title: Ntense Technologies
        sub_title: IT Technician
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          -Description of role
          -Description of role
                                     
  - title: Education
    layout: list
    content:
      - layout: left
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     When I unplug, I make the most of my time outdoors. I'm into wakesurfing on Lake Lanier and rollerblading along the Atlanta Beltline. 
     Years ago, I took part a long-distance inline skating race across open roads of Georgia called Athens to Atlanta Road Skate.
     I completed the race which is roughly 87 mile in about 8 hours. It's accomplishment story that i always want to tell. 
     
     Originally from South Louisiana, Cajun culture is in my roots. Since moving to Atlanta, I’ve had the chance to explore all kinds of new cuisines, 
     and Indian food has quickly become one of my favorites cuisine—thanks to some awesome former housemates who introduced me to it. These days, I can’t resist a good thali plate!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
