# Site
repository:

# Content configuration version
version: 2

# Personal info
name: Dane Gauthier
#title: Your job title
email1: Dane@danegauthier.tech
email2: Danegauthier@gmail.com
# email_title: 
# phone: 
# phone_title: 
# website: 
# website_title: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  danegauthier
linkedin_username: danegauthier

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hey, I’m Dane. Over the past 15 years, I’ve worked in various End-User Support roles. 
 Along the way, I developed skills in various Microsoft solutions such as Azure, AVD, and Intune/SCCM.
 I created this site to showcase technical projects and share more details about my professional background.
 
content:
  - title: Projects 
    layout: list 
    content:
      - layout: top-middle
        border: weak  
        title: danegauthier.tech
        link: github.com/danegauthier/danegauthier.github.io
        link_text: danegauthier/danegauthier.github.io
        # additional_links:
        #  - title: github.com/danegauthier/danegauthier.github.io
        #    icon: fab fa-github
        #    url: github.com/danegauthier/danegauthier.github.io
        quote: >

        description: | # this will include new lines to allow paragraphs
         This website is built using a Jekyll theme and hosted as a static site on GitHub Pages.
         During development, I gained experience with HTML/CSS, GitHub commands and repository 
         management, and Docker for local testing. Link above to the GitHub repository.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Fisher & Phillips (CDW)
        sub_title: Refresh Technical
        caption: May 2024 - Aug 2024
        link: 
        quote: >
          National law firm specializing in labor and employment law for employers 
        description: | 
          Assisted in a hardware refresh project by transitioning employees and law partners from Windows 10 to Windows 11 laptops. Handled end-to-end data migrations, application installations, 
          and system configurations in line with standardized deployment protocols to deliver a seamless user experience. Prepared laptops using Autopilot pre-provisioning steps and decommissioned 
          outdated hardware. Escalated out-of-scope technical issues through the ticketing system to ensure prompt resolution by the appropriate support teams.
      - layout: left
        title: Thyssenkrupp Materials (TEKsystems) 
        sub_title: Azure Virtual Desktop Specialist
        caption: July 2023 - October 2023
        link: thyssenkrupp-materials-na.com
        quote: >
           Global supplier of materials for the manufacturing and construction industries 
        description: | 
          Delivered second-level support for the Azure Virtual Desktop environment, resolving abnormal network connectivity, warehouse printer issues, and thin-client issues to minimize downtime. 
          Collaborated on patching host-pool virtual machines and rolling out software updates to increase system security and compliance across the AVD infrastructure. Designed and implemented a 
          host-pool utilization report that enabled accurate departmental invoicing and informed strategic resource planning.
      - layout: left
        title: CONA Services (TEKsystems)
        sub_title: Senior IT Support Specialist
        caption: June 2022 - June 2023
        link: conaservices.com
        quote: >
          Provides IT solutions for Coca-Cola bottlers in North America. 
        description: | 
         Provided support for on-site and remote employees across all levels, addressing hardware, software, and office technology issues. Served as the primary Intune administrator, 
         leading device management initiatives such as Autopilot deployment, Windows 11 migrations via Feature Updates, and Microsoft LAPS implementation. Acted as the subject matter expert 
         for the Azure Virtual Desktop environment, serving as the final escalation point and driving improvements including host pool autoscaling, optimized VM sizing, automated software updates 
         with Winget, and strengthened security configurations. Supported enterprise-wide Microsoft 365 services, including Entra, Exchange, Teams, PowerApps, and SharePoint.
      - layout: left
        title: Scientific Games
        sub_title: End-User Computing Engineer
        caption: June 2019 - November 2021
        link: scientificgames.com
        quote: >
          Global leader in lottery games, casino technologies, and services for government-sponsored lotteries. 
        description: |
          Provided Tier 3 technical support for the North America service desk, assisting onsite and remote employees with hardware, software, and office technology issues. 
          Played a key role in the company-wide Windows 10 migration by developing and supporting OSD migration processes within SCCM and guiding service desk teams through migration support. 
          Deployed Azure Virtual Desktop solutions to enable remote work during the pandemic and company divestiture, addressing hardware shortages by creating images and security policies for 
          personal and pooled host pools. Supported hardware budgeting and procurement by developing SCCM-based reports to inform equipment replacement and new hire purchasing decisions.   
      - layout: left
        title: Artivion
        sub_title: Information Systems Specialist III
        caption: August 2017 - January 2019
        link: artivion.com
        quote: >
          Medical device company specializing in aortic disease treatments, including stent grafts, heart valves, and sealants. 
        description: | 
         Supported hardware and software needs for onsite staff, sales teams, and European offices while expanding responsibilities to include administration of Office 365, SCCM, JAMF, 
         and Avaya phone systems. Led the transition from WDS to SCCM for Windows PC imaging by developing task sequences and packaging applications to ensure consistent deployment across 
         the hardware fleet. Played a key role in launching a Mac user-choice program by managing JAMF, establishing baseline processes, and migrating sales and executive teams from Windows 
         to Mac devices. Provided IT support for international sales conferences, participated in overseas cross-training following an acquisition, and earned JAMF 200 certification.
      - layout: left
        title: UCB Pharma (Hays)
        sub_title: Desktop Support Technician
        caption: March 2016 - July 2017 
        link: ucb.com
        quote: 
          Global biopharmaceutical company focused on innovative medicines for severe immunology and neurology diseases.
        description: | 
          Independently led a lease-end laptop refresh project replacing approximately 200 laptops. Migrated data and user settings, deploying user-assigned software, 
          and imaging through SCCM. Coordinated with employees to ensure a smooth transition. Provided new-hire orientations for corporate equipment to ensure smooth onboarding. 
          Delivered Level 2 on-site support for hardware, business applications, mobile devices, and desk relocations, managed asset management using BMC Helix ITSM.
      - layout: left
        title: Walmart (Compucom)
        sub_title: Lead Field Refresh Technician
        caption: August 2015 - December 2015
        link: 
        quote: 
        description: | 
         Windows XP to Windows 7 refresh project, Traveled to Walmart stores across South Louisiana to upgraded kiosks, pharmacy, and management workstations. 
         Supported technicians in following a replacement process, troubleshooting issues during migration, and escalating out-of-scope problems to the project team. 
         Completed post-migration tasks, including logging upgraded inventory and preparing replaced equipment for return to the project warehouse.
      - layout: left
        title: CBM Technology
        sub_title:  IT Specialist
        caption: July 2011 - February 2015
        link: cbm.technology
        quote: |
          Managed IT service provider in Breaux Bridge, LA 
        description: | 
         Provided on-site and remote IT support across diverse sectors including government, sugar production, education, law enforcement, legal services, oil & gas, and retail. 
         Handled a wide range of technical issues from routine hardware and software troubleshooting to new PC setups, software deployments, network cabling, and full domain and Exchange migrations. 
         Maintained detailed work logs in ConnectWise to ensure accurate tracking and billing. Served as the dedicated onsite sysadmin for a major client, managing technical issues, projects, 
         PC refreshes, and administering Active Directory and Exchange.
      - layout: left
        title: Ntense Technologies
        sub_title: IT Technician
        caption: July 2008 - June 2011
        link: 
        quote: 
          Small  IT consulting company in Lafayette, LA
        description: | 
         Started my IT support career providing on-site to clients across diverse industries, troubleshooting hardware and software issues, configuring new PCs, 
         and supporting network cabling jobs. Gained valuable experience managing Active Directory and Exchange, as well as network troubleshooting.
       
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: South Louisiana Community College
        sub_title: A.S. Information Technology 

  # - title: Beyond the Resume
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Outdoor enthusiast into wakesurfing, rollerblading, and hiking. Born in South Louisiana, living in Georgia since 2016

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
