# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Dane Gauthier
#title: Your job title
email1: Dane@danegauthier.tech
email2: Danegauthier@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dane-gauthier
linkedin_username: danegauthier
resume_username: dane-gauthier

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hey, I’m Dane Gauthier. I’ve been solving desktop and cloud tech challenges for over 15 years, with a current focus on Azure Virtual Desktop. I’m exploring my next opportunity, and I put this together to share a bit of how I think and what I can bring to a team.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  
        title: danegauthier.tech
        link: github.com/danegauthier/danegauthier.github.io
        link_text: danegauthier/danegauthier.github.io
        additional_links:
          - title: github.com/danegauthier/danegauthier.github.io
            icon: fab fa-github
            url: github.com/danegauthier/danegauthier.github.io
        quote: >
           
        description: | # this will include new lines to allow paragraphs
         The resume site is Jekyll theme that I learned how to change everything on it. This taught me about static generated sites, GitHub, and Docker. 
  - title: Experience
    layout: list
    content:
      - layout: left
        title: UPS 
        sub_title: Automation Support Technician
        caption: September 2024  - March 2025
        link: 
        quote: >
           
        description: | # this will include new lines to allow paragraphs
          I help keep UPS’s automated conveyor systems running smoothly by quickly troubleshooting jams, scanner errors, and mechanical issues. 
          I work with ops and maintenance to minimize downtime and spot routing issues early.  
      - layout: left
        title: Fisher & Phillips (CDW)
        sub_title: Refresh Technical
        caption: May 2024 - Aug 2024
        link: Link to company (optional)
        quote: >
          National law firm specializing in labor and employment law for employers 
        description: | # this will include new lines to allow paragraphs
         At Fisher & Phillips, I handled the full laptop lifecycle refresh for over 400 Dell systems—upgrading them from Windows 10 to 11. 
         I managed user data migration through OneDrive and network solutions and manually configured core business applications (since we weren’t using scripts). 
         I stuck closely to deployment processes, handled any tech hiccups as they popped up, and made sure users were good to go before wrapping up migration sessions.
      - layout: left
        title: UPS 
        sub_title: Automation Support Technician
        caption: November 2023 - March 2024
        link: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          I help keep UPS’s automated conveyor systems running smoothly by quickly troubleshooting jams, scanner errors, and mechanical issues. 
          I work with ops and maintenance to minimize downtime and spot routing issues early, helping our team stay on track with operations goals.  
      - layout: left
        title: Thyssenkrupp Materials (TEKsystems) 
        sub_title: Azure Virtual Desktop Specialist
        caption: July 2023 - October 2023
        link: Link to company (optional)
        quote: >
           Global supplier of materials for the manufacturing and construction industries 
        description: | # this will include new lines to allow paragraphs
         Short but impactful stint! I supported second- and third-level AVD tickets and worked with the lead engineer on weekly updates to the Change Advisory Board. 
         I built Azure Insight reports to monitor host pool usage and troubleshoot latency. 
         I also collaborated closely with our MSP, Logicallas, to keep the cloud environment running smoothly.
      - layout: left
        title: CONA Services (TEKsystems)
        sub_title: Senior IT Support Specialist
        caption: June 2022 - June 2023
        link: Link to company (optional)
        quote: >
          Provides IT solutions for Coca-Cola bottlers in North America. 
        description: | # this will include new lines to allow paragraphs
         I was the go-to AVD expert here, supporting 500 concurrent users globally. 
         I handled software updates using winget, onboarded Windows 365 Cloud PCs for remote teams, and led the transition to Windows 11 using Intune, Autopilot, and LAPS. 
         I also worked on building out our internal knowledge base and provided support both onsite and remotely. 
      - layout: left
        title: Scientific Games
        sub_title: End-User Computing Engineer
        caption: June 2019 - November 2021
        link: 
        quote: >
          Global leader in lottery games, casino technologies, and services for government-sponsored lotteries. 
        description: | # this will include new lines to allow paragraphs
         I supported Tier 3 issues across North America and managed AVD deployments. 
         I worked with procurement on quarterly hardware budgets for 2,000+ devices, administered MECM, and improved our image deployment process. 
         I also led automation efforts and built a self-service system for updates, plus met regularly with global teams to coordinate image changes and stay compliant with security standards.     
      - layout: left
        title: Artivion
        sub_title: Information Systems Specialist III
        caption: August 2017 - January 2019
        link: 
        quote: >
          medical device company specializing in aortic disease treatments, including stent grafts, heart valves, and sealants. 
        description: | # this will include new lines to allow paragraphs
          Here, I managed both Windows and Mac support, built the initial SCCM OS deployment framework, and used JAMF to standardize Mac environments. 
          I also handled Active Directory tasks—like Group Policy, DHCP, and DNS.
      - layout: left
        title: UCB Pharma (Hays)
        sub_title: Desktop Support Technician
        caption: March 2016 - July 2017 
        link: 
        quote: >
          Global biopharmaceutical company focused on innovative medicines for severe immunology and neurology diseases.
        description: | # this will include new lines to allow paragraphs
         I supported 1,500 users onsite, completed PC refresh projects, and improved first-contact resolution by 40% within six months. 
         I also conducted new hire tech onboarding and offered app and security support.
      - layout: left
        title: Walmart (Compucom)
        sub_title: Lead Field Refresh Technician
        caption: August 2015 - December 2015
        link: 
        quote: >

        description: | # this will include new lines to allow paragraphs

      - layout: left
        title: CBM Technology
        sub_title:  IT Specialist
        caption: July 2011 - February 2015
        link: www.cbm.technology
        quote: >
          Managed IT service provider in Breaux Bridge, LA 
        description: | # this will include new lines to allow paragraphs
         Provided support (on-site and remote) for clients in sectors like local and state government, sugar production, school districts, law enforcement, legal services, oil&gas and retail. 
         Technical issues from everyday hardware and software troubleshooting to new PC setups, software rollouts, network cabling, and full migrations domains and exchange. 
         Responsible for maintaining detailed work logs in ConnectWise to support accurate tracking and billing. 
         During a period my main responsibilities was serving as the dedicated onsite sysadmin for a large client. I would report onsite after our company standup meetings.
         Addressing tech issues, technical projects, PC refreshes, administered changes Active Directory, Group Policy, and Exchange, supported a custom HRIS solution for client industry.
      - layout: left
        title: Ntense Technologies
        sub_title: IT Technician
        caption: July 2008 - June 2011
        link: 
        quote: >
          Small  IT consulting in Lafayette, LA
        description: | # this will include new lines to allow paragraphs
          This was my first gig in the tech world while I was still in college. Basically, I was the go-to person for setting up computers at client offices and hauling equipment between their office and ours. 
          I also did a ton of network cabling jobs. Back then, spyware and malware were a real headache, so some days I'd be in the office, cleaning computers. 
          It was a great learning experience – I picked up a lot about setting up computer images and even got to know the ins and outs of wireless internet equipment. 
          Our clients span various sectors, from law enforcement and legal firms to student housing, the oil&gas industry, and retail.
                                     
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: South Louisiana Community College
        sub_title: A.S. Information Technology 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
     When I unplug, I make the most of my time outdoors. I'm into wakesurfing on Lake Lanier and rollerblading along the Atlanta Beltline. 
     Years ago, I took part a long-distance inline skating race across open roads of Georgia called Athens to Atlanta Road Skate.
     I completed the race which is roughly 87 mile in about 8 hours. It's accomplishment story that i always want to tell. 
     
     Originally from South Louisiana, Cajun culture is in my roots. Since moving to Atlanta, I’ve had the chance to explore all kinds of new cuisines, 
     and Indian food has quickly become one of my favorites cuisine—thanks to some awesome former housemates who introduced me to it. These days, I can’t resist a good thali plate!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
