# Site settings
name: Dane Gauthier
email: Dane@danegauthier.com  
url: 
description: "A blog and a portfolio"
author: ""
title: ""
permalink: pretty
baseurl: 

# social
github:
  username: dane-gauthier

linkedin:
  username: danegauthier

credly:
  username: dane-gauthier